# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e5a59a0c4f15bbf0a63e16d793479a13c48266f64588d96f73b8c9d7ea872d46c5bf5a928579422f448005d2cf56fcc56124a8410ce3f8eaeed9fc31c94300d

test:
  secret_key_base: 316591b8a44967dae21f861981e9c9d9d0b7c05fece8afc3ba13fbd68b44664b905922100ad8f6c131387fe65cb6b69ec4b7e930ba5755c7f069f8db9a926a45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
